# Generated by Django 4.0 on 2022-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtext', models.TextField()),
                ('comments', models.TextField()),
                ('bloger', models.CharField(max_length=8)),
            ],
        ),
    ]
