# Generated by Django 4.0 on 2022-11-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogpost',
            field=models.TextField(null=True),
        ),
    ]
