# Generated by Django 4.0 on 2022-11-21 09:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogs/default.jpg', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='bloger',
            field=models.CharField(max_length=100),
        ),
    ]
